Ext.define('KCCVBS.model.Children', {
    extend: 'Ext.data.Model',
    fields: [
                'ChildrenKey',
                'Active',
                'NeighborhoodKey',
                'AgeKey',
                'ClassKey',
                'FirstName',
                'LastName',
                'Address1',
                'Address2',
                'City',
                'State',
                'Zip',
                'Phone',
                'Mobile',
                'Parent',
                'GradeCompleted',
                'Email',
                'DOB',
                'Age',
                'SpecialNeeds',
                'Notes',
                'Monday',
                'Tuesday',
                'Wednesday',
                'Thursday',
                'Friday',
                'Saturday',
                'Sunday',
                'EntryDate',
                'CreateDate',
                'CreatedBy',
                'EditDate',
                'EditedBy'
            ]
});
